//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public long EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string Department { get; set; }
        public string MailID { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public Nullable<long> Phone { get; set; }
        public string Address { get; set; }
        public Nullable<long> Salary { get; set; }
        public Nullable<int> Age { get; set; }
    }
}
